### ISSUE TITLE
[feat][bug] 리뷰 별점 시 한식 뷔페 테이블에 별점 업데이트 기능 누락

### ISSUE THREAD

**Issue by chobkyu** [chobkyu/hansig-server#47]
현재 리뷰에 별점을 주는 기능이 포함이 되어 있습니다.

다만 리뷰에 별점이 달리면 hansics 테이블에서도 userstar가 업데이트가 되어야하는데 그 기능이 누락되어 있습니다.

기능 추가 요청 드립니다.

userstar는 해당 뷔페가 받은 별점의 평균을 저장해주시면 될 거 같습니다.

@jeon0711

**Comment by jeon0711** [comment]
확인했습니다. 내일 시작하도록 하겠습니다.
