### ISSUE TITLE
리뷰 이미지 업로드 문제

### ISSUE THREAD

**Issue by cxzaqq** [chobkyu/hansig-server#62]
![image](https://github.com/chobkyu/hansig-server/assets/100334032/602ac13b-2832-4434-92c6-d7ea682aa928)

이렇게 요청 넣으면 에러가 뜹니다. 따로 statusCode가 오는 게 아니라 TimeOut입니다.

url, header, body에는 이상이 없어보입니다.

확인 부탁드립니다!!

**Comment by chobkyu** [comment]
서버로그는 확인해보셨나요?

**Comment by cxzaqq** [comment]
헐 제 잘못이네요.. 죄송합니다
